name: Code Quality Assurance

on:
  push:
  pull_request:

jobs:
  qa:
    name: QA - OS ${{ matrix.os }}, Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [21.x, 22.x, 23.x]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Biome CLI
      uses: biomejs/setup-biome@v2
    - name: Run Biome
      run: biome ci
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Build package
      run: npm run prod
    - name: Run tests
      run: npm run test
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '23.x' }}
    - name: SonarQube scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '23.x' }}
